### ISSUE TITLE
Cannot use string offset as an array

### ISSUE THREAD

**Issue by thiagomoraesp** [bozhinov/pChart2.0-for-PHP7#1]
Hi dude, first of all thanks for the amazing job porting this library to php7, it really save my life a lot of times, but now i have a serious issue and need some help =(
The module is not working with the newer php version (7.1.1), its giving the message **"Cannot use string offset as an array"** In the **line 80 of pData.class.php**
Can you please help me? thanks in advance ;)

ps: there are anyway to donate for the project?

**Comment by bozhinov** [comment]
Hi,

Thanks. It took some time but I really needed the lib. Was not sure anyone used it any more

You can donate to the main project:
http://www.pchart.net/license

Jean-Damien (the original author) is a cool dude

Can you prep a sample piece of code ? 
I have not yet tested 7.1.1, but it used to work ok with 7.1.0
Any I will be back to civilization in a day or two and will take a look

**Comment by bozhinov** [comment]
Seems that php 7.1.1 is not such a small release after all.
I noticed the work around the extract function in the php git, but did not expect it to have such an effect

Did some minor changes to the examples. Just enough to make them compatible.
There are at least two problem here:
- one would be the use of Extract, which I introduced
- the other one is in the pData class and indexing into a non-existent branch

Will fix those on Monday

**Comment by thiagomoraesp** [comment]
Thank you for the response, as gratitude in the next week i will submit a pull request to make it composer compatible with a composer.json =)

**Comment by bozhinov** [comment]
Ok, so all problems with the Example scripts have been solved for PHP 7.1.1
None of those seem to address your issue though

I will need that sample code after all

**Comment by thiagomoraesp** [comment]
Here it goes:

http://pastebin.com/gUCxp36m

**Comment by bozhinov** [comment]
I will need the input data as well
try echo json_encode($valores) and  json_encode($legendas)

By the way .. starting PHP7 .. that @ is not supressing anything (@$myPicture = new pImage(550,140,$MyData);)

**Comment by thiagomoraesp** [comment]
Here it is the $dados variable as Json

```
[
  {
    "cor": "l",
    "porcentagem": 30.3,
    "descricao": "Realizador \/ Empreendedor"
  },
  {
    "cor": "a",
    "porcentagem": 19.7,
    "descricao": "Organizador \/ Estruturador"
  },
  {
    "cor": "v",
    "porcentagem": 20.45,
    "descricao": "Social \/ Relacional"
  },
  {
    "cor": "b",
    "porcentagem": 15.91,
    "descricao": "Inovador \/ Pensador"
  },
  {
    "cor": "m",
    "porcentagem": 13.64,
    "descricao": "Integrador \/ Sist\u00eamico"
  }
]
```

**Comment by bozhinov** [comment]
I will need that one as well - /resources/cores.php

If I omit the $PieChart->setSliceColor routine, the image reneders OK

**Comment by thiagomoraesp** [comment]
here:

http://pastebin.com/RwKA68n7

**Comment by bozhinov** [comment]
Renders without even a notice

http://bojinov.info/momchil/issue1/relacoes-360-fotografia-avaliadores.png
http://bojinov.info/momchil/issue1/test.zip

**Comment by thiagomoraesp** [comment]
So you can't reproduce the error in your php 7.1.1? Or you modified my code?

**Comment by bozhinov** [comment]
I modified it for sure as it includes parts of your framework but the end result shoult be the same

The input data is the same - $dados
$cores[$dado['cor']]['R'] - cores.php includes the colors with where - VERDE = v, LARANJA = l and so on

http://bojinov.info/momchil/issue1/test.zip
is the code that I used. Take a look at it

**Comment by thiagomoraesp** [comment]
Thank you, i will test it tomorrow =)

**Comment by thiagomoraesp** [comment]
I tested it, and it worked at the first try(are you a wizard? Lol).
Thank you so much =)

**Comment by bozhinov** [comment]
Glad to hear it. I don't think I had anything to do with the resolution though :)
