### ISSUE TITLE
Thanks! How can we help?

### ISSUE THREAD

**Issue by eclipxe13** [bozhinov/pChart2.0-for-PHP7#10]
Thanks for the work you have done making compatible pChart2 with PHP 7.1.

What can I (or others) do for helping you?
Do you have a ToDo list or some tasks/ideas?

**Comment by bozhinov** [comment]
Hi,

Well, any bug report or feature request is welcomed
Good enough of help for me

As for the short term todo list:
- turn color into a separate class that you can work with  - that part is almost done
It simplified the code significantly, but there is still room for improvement
- rewrite the JS for the ImageMapper using jQuery - that part hasn't started yet.

Long term I m planing on cheking what other types of charts I can add .. like pyramid.
Also at least few other types of barcodes.
The original author had this idea to add a world map and make it possible to interact with it

pChart could be used for way more than just charts

I was thinking about separting the GD from the computing code and make it possible to use other drawing libraries like ImageMagic and Vips, but nowadays it seems to be all about the JS. I m surprised anyone but me is still using pChart.

Regards,
Momchil
