### ISSUE TITLE
Minor error

### ISSUE THREAD

**Issue by jjlazo79** [bozhinov/pChart2.0-for-PHP7#11]
Hi,

I try to create a radar with this library and get an error:
`[Tue Jan 09 14:21:23.523768 2018] [:error] [pid 10832:tid 1172] [client ::1:52810] PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in C:\\wamp\\www\\gogood\\web\\wp-content\\plugins\\report-builder\\pChart2.0\\class\\pDraw.class.php on line 623, referer: http://localhost/gogood/web/mi-cuenta/view-order/2244/`

In branch 7.x-compatible pChart2.0-for-PHP7\\class\\pDraw.class.php on line 623 I found this:
`/* Drawn a spline based on the bezier function */
	function drawSpline(array $Coordinates, array $Format = []): array {`

And change to this:
`/* Drawn a spline based on the bezier function */
	function drawSpline(array $Coordinates, array $Format = [])
{`

Now work fine. Thanks for the job.

**Comment by bozhinov** [comment]
Hi,

Thank you for that

I assume you are using PHP 7,0 ?

Momchil

**Comment by jjlazo79** [comment]
Hi,

I used PHP: 7.1.5

**Comment by bozhinov** [comment]
That's weird. I pushed the fix anyway, as the check was only needed during the refactoring.

Can you please check with latest 7.1 ? Just to please my curiosity

yesterday I tested all of the code with all current PHP versions and found no issues

**Comment by bozhinov** [comment]
Found a problem with my testing

No need for further verification
