### ISSUE TITLE
license

### ISSUE THREAD

**Issue by splitbrain** [bozhinov/pChart2.0-for-PHP7#12]
Hi,

it's great that this got picked up again. If I remember correctly, the original pChart was licensed under GPL2 or higher. You went for GPL3 which is of course fine, but makes it unusable for us folks maintaining GPL2 only software (DokuWiki in my case). Would it make a huge difference for you to license this under GPL2+?

**Comment by bozhinov** [comment]
Hi,

I downloaded the latest available on the official pChart website:
http://www.pchart.net/release/pChart2.1.4.zip

It contains GPLv3.txt

Momchil
