### ISSUE TITLE
Radar Chart Series Colors

### ISSUE THREAD

**Issue by bergenrothn97** [bozhinov/pChart2.0-for-PHP7#18]
I'm having an issue when I plot multiple series on the same radar chart. The color of each series is the same, but the legend properly displays the change in colors for each series correctly. Can anyone help? It makes it difficult to read the graph for each set of data if the color does not change on the graph.

**Comment by bergenrothn97** [comment]
Yes, I am using the new version that it compatible with PHP 7.1 +

Thanks in advance for your help.

function savegraphs($peopleid, $userid) {
	include("class_jake.php");
	include 'connection to db';
	include 'configuration file';
	include 'pChart/pData.php';
	include 'pChart/pRadar.php';
	include 'pChart/pDraw.php';
	include 'pChart/pColor.php';
	include 'pChart/pColorGradient.php';
	include 'pChart/pException.php';
	include 'pChart/pCharts.php';

/* Create the pChart object */
$myPicture = new pDraw(825,390);
	
 // Dataset definition 
 $MyData = new pData();
$MyData2 = new pData();
	$pointsarray = array();
	
	$arrlength = count($peopleid);

for($x = 0; $x < $arrlength; $x++) {
	// query that pulls info from the database (it is a six value series) I have edited our for security purposes.

	$statement2 = $dbhandle->prepare(""); 

		while ($row2 = $statement2->fetch()) {
				
			$name = $row2["FirstName"] . " " . $row2["LastName"];
			
			$seriesname = $row2["FirstName"] . " " . $row2["LastName"] . $x;

	$statement = $dbhandle->prepare("SELECT * FROM diagnsoticvalues where personid =? order by sortorder asc");
		if ($statement->execute(array($peopleid[$x]))){
			
			while ($row = $statement->fetch()) {
				
				$date = date_create($row['datesubmitted']);
				
				$point = jake($row["score"]) ;
				
				array_push($pointsarray, $point);			
			}
			
			$myPicture->myData->addPoints($pointsarray, $seriesname);
			$date = date_format($date, 'd/m/y');
			$name.=" - (".$date.")";
			$myPicture->myData->setSerieDescription($seriesname,$name);
			
		}
	
}
			
		}
	
$color = new pColor(179,217,91) ;

$htmllogo="images/rowingcoachinglogo.png";
	
/* Define the abscissa serie */
$myPicture->myData->addPoints(["Drive","Concentration","Spirit and Confidence","Self-Management","External Motivation","Internal Motivation"],"Labels");
$myPicture->myData->setAbscissa("Labels");

/* Draw a solid background */
$myPicture->drawFilledRectangle(0,0,825,390,["Color"=>new pColor(179,217,91), "Dash"=>TRUE, "DashColor"=>new pColor(199,237,111)]);
	
/* Overlay some gradient areas */
$myPicture->drawGradientArea(0,0,825,390,DIRECTION_VERTICAL,["StartColor"=>new pColor(188,210,218,100),"EndColor"=>new pColor(128,170,184,100)]);
	
$myPicture->drawGradientArea(0,0,825,50, DIRECTION_VERTICAL,["StartColor"=>new pColor(0,0,0,100),"EndColor"=>new pColor(0,0,0,100)]);
	
/* Add a border to the picture */
	
$myPicture->drawRectangle(0,0,824,389,["Color"=>new pColor(0,0,0)]);
	
/* Write the picture title */ 
$myPicture->setFontProperties(array("FontName"=>"fonts/tahoma.ttf","FontSize"=>24));
$myPicture->drawText(10,42,"Competitive Athlete Psychology Diagnostic Results",["Color"=>new pColor(255,255,255)]);
/* Set the default font properties */ 
$myPicture->setFontProperties(array("FontName"=>"fonts/tahoma.ttf","FontSize"=>14,"Color"=>new pColor(80,80,80)));
/* Enable shadow computing */ 
$myPicture->setShadow(FALSE,["X"=>2,"Y"=>2,"Color"=>new pColor(0,0,0,10)]);
//$myPicture->setShadow(FALSE,array("X"=>2,"Y"=>2,"R"=>0,"G"=>0,"B"=>0,"Alpha"=>10));
/* Create the pRadar object */ 
$SplitChart = new pRadar($myPicture);
	
/* Draw a radar chart */ 

$myPicture->setGraphArea(0,60,700,390);
	
$Options = [
	"Layout"=>RADAR_LAYOUT_CIRCLE,
	"LabelPos"=>RADAR_LABELS_HORIZONTAL, "FixedMax"=>100, "SegmentHeight"=>20, "Segments"=>5,
	"BackgroundGradient"=>["StartColor"=>new pColor(255,255,255,50),"EndColor"=>new pColor(32,109,174,30)],
	"FontName"=>"fonts/tahoma.ttf","FontSize"=>12
];
$SplitChart->drawRadar($Options);
/* Write the chart legend */ 
$myPicture->setFontProperties(["FontName"=>"fonts/tahoma.ttf","FontSize"=>12]);

$myPicture->drawFromPNG(600,200,$htmllogo);

$myPicture->drawLegend(600,80,["Style"=>LEGEND_NOBORDER,"Mode"=>LEGEND_VERTICAL]);

/* Render the picture */
$myPicture->Render("images/team_" . $userid . ".jpg");
	
	$dbhandle=null;	

}
	
}

**Comment by bozhinov** [comment]
Here is what I get
[http://bojinov.info/github/team_userid.jpg](url)

**Comment by bergenrothn97** [comment]
Here is the data dump.

{"XAxisDisplay":680001,"XAxisFormat":null,"XAxisName":null,"XAxisUnit":null,"Abscissa":null,"AbsicssaPosition":681002,"Axis":[{"Display":680001,"Position":681001,"Identity":682002}],"Series":{"Joe Jenkins0":{"Description":"Joe Jenkins - (01\/05\/18)","isDrawable":true,"Picture":null,"Max":0,"Min":0,"Axis":0,"Ticks":null,"Weight":null,"Shape":681011,"Color":{"R":188,"G":224,"B":46,"Alpha":100},"Data":[58,46,58,42,54,67]},"Joe Smith1":{"Description":"Joe Smith - (23\/04\/18)","isDrawable":true,"Picture":null,"Max":0,"Min":0,"Axis":0,"Ticks":null,"Weight":null,"Shape":681011,"Color":{"R":224,"G":100,"B":46,"Alpha":100},"Data":[58,46,58,42,54,67,42,58,50,58,83,67]}}}

**Comment by bergenrothn97** [comment]
I figured it out. Both data sets were going into the same array. So the first dataset was not making it. It was a logic issue with my code. Thanks for the help, I appreciate it very much.

**Comment by bozhinov** [comment]
I noticed that the data for Joe Smith1 contains the data for Joe Jenkins0

"Data":[58,46,58,42,54,67,42,58,50,58,83,67]
"Data":[58,46,58,42,54,67]

but even then the color of the legend does not reflect the color in the radar.
problem is by looking at the code I don't think that it ever worked like that

Can you still send a screenshot of your final result ?

**Comment by bergenrothn97** [comment]
![team_62](https://user-images.githubusercontent.com/38902063/39549762-afad366a-4e24-11e8-8e57-fe3517eadbd2.jpg)
``

**Comment by bozhinov** [comment]
Fellow rower
Ok Then.Looks good. I m closing this
