### ISSUE TITLE
Invert Y axis and format for m:s

### ISSUE THREAD

**Issue by bergenrothn97** [bozhinov/pChart2.0-for-PHP7#19]
I'm trying to invert the y axis and then display the 500m split (raw data in seconds). Any clue how to accomplish this? Right now the units are in seconds. 

![scatter_94](https://user-images.githubusercontent.com/38902063/40152620-9d02aeb4-594b-11e8-9595-a11eb8b357d3.png)

**Comment by bozhinov** [comment]
not on top of my head, no.
but you remember last time  - I need sample code and json encoded dump of $pchart->MyData->getData();

**Comment by bergenrothn97** [comment]
Here is the data dump:

{"XAxisDisplay":680001,"XAxisFormat":"XAxisFormat","XAxisName":null,"XAxisUnit":null,"Abscissa":"dateofrow","AbsicssaPosition":681001,"Axis":[{"Display":680007,"Position":681001,"Identity":682002,"Name":"Average Split in Seconds","Unit":"s","Format":"NegateValues","Min":-121.04,"Max":-116.96,"Margin":0,"ScaleMin":-122,"ScaleMax":-116,"Rows":6,"RowHeight":1},{"Identity":682001,"Position":681001,"Name":"Dates","Margin":100,"Rows":2,"Display":null,"Format":null,"Unit":null}],"Series":{"split":{"Description":"Split Rowed","isDrawable":true,"Picture":null,"Max":-117,"Min":-121,"Axis":0,"Ticks":null,"Weight":null,"Shape":681011,"Color":{"R":188,"G":224,"B":46,"Alpha":100},"Data":[-121,-119,-117],"XOffset":0},"dateofrow":{"Description":"Sampled Dates","isDrawable":true,"Picture":null,"Max":0,"Min":0,"Axis":0,"Ticks":null,"Weight":2,"Shape":681011,"Color":{"R":224,"G":100,"B":46,"Alpha":100},"Data":["2018-04-29","2018-04-30","2018-05-09"]}},"AbscissaName":"Dates","Orientation":690101,"YMargin":0}

**Comment by bergenrothn97** [comment]
Here is the function that generates the graph. Many thanks in Advance, fellow rower. 

function tryingagain($athleteid, $workoutid) {
	
	include ('dbconn.php');
	include 'pChart/pData.php';
	include 'pChart/pRadar.php';
	include 'pChart/pDraw.php';
	include 'pChart/pColor.php';
	include 'pChart/pColorGradient.php';
	include 'pChart/pException.php';
	include 'pChart/pCharts.php';
	include '../../.bu94/config.php';
	
	$myData = new pData(); 
	$dateofrow = array();
	$splitthatday = array();
	$myPicture = new pDraw(700,230);
	$actualdate = "";
	
	
	$statement = $dbhandle->prepare("select * from workoutmaster where athleteid = ? and workoutidv2 = ? and actualsplit <> '00:00:00.0' order by date asc");
	
	$statement->execute(array($athleteid, $workoutid));
	
	$count = $statement->rowCount();
	
	if ($count > 0) {
		
		$count = 1;
	
			while ($row = $statement->fetch()) {
			
				$title = $row['title'];
				$point = $row['date'] ;
				//$pointdate = strtotime($point);
				//echo $pointdate;
					
				$pointsplit = $row['actualsplit'];
				
				if ($pointsplit == "00:00:00.0") {
					
				} else {
					
			//$actualdate = gmdate("Y-m-d", $pointdate);
					
		$str_time = $pointsplit;

$str_time = preg_replace("/^([\d]{1,2})\:([\d]{2})$/", "00:$1:$2", $str_time);

sscanf($str_time, "%d:%d:%d", $hours, $minutes, $seconds);

$time_seconds = $hours * 3600 + $minutes * 60 + $seconds;
					
					
array_push($dateofrow, $point);		
				
array_push($splitthatday, $time_seconds);
				
				$count = $count+1;		
				}		
		}
	
$myPicture->myData->addPoints($splitthatday, "split");
$myPicture->myData->addPoints($dateofrow, "dateofrow");
	
$myPicture->myData->setSerieWeight("dateofrow",2);

$myPicture->myData->setAxisName(0,"Average Split in Seconds"); 
$myPicture->myData->setAxisUnit(0,"s"); 

$myPicture->myData->setSerieDescription("split","Split Rowed");
$myPicture->myData->setAbscissa("split");

/* Reverse the Y axis trick */
$myPicture->myData->setAbsicssaPosition(AXIS_POSITION_TOP);
$myPicture->myData->NegateValues(array("split"));
$myPicture->myData->setAxisDisplay(0,AXIS_FORMAT_CUSTOM,"NegateValues");
	
$myPicture->myData->setSerieDescription("dateofrow","Sampled Dates");
$myPicture->myData->setAbscissa("dateofrow");
$myPicture->myData->setAbscissaName("Dates");
//$myPicture->myData->setXAxisDisplay(AXIS_FORMAT_DATE);
$myPicture->myData->setXAxisDisplay(AXIS_FORMAT_DEFAULT,"XAxisFormat"); 
 
	
function NegateValues($Value) {
	return ($Value == VOID) ? VOID : -$Value;
}

$AxisBoundaries = array(0=>array("Min"=>90,"Max"=>150));
$ScaleSettings = array("Mode"=>SCALE_MODE_MANUAL,"ManualScale"=>$AxisBoundaries);
 
	
$myPicture->drawFilledRectangle(0,0,700,230,["Color"=>new pColor(170,183,87), "Dash"=>TRUE, "DashColor"=>new pColor(190,203,107)]);
	
$myPicture->Antialias = TRUE;
	
	
$myPicture->drawGradientArea(0,0,700,230,DIRECTION_VERTICAL, ["StartColor"=>new pColor(188,210,218,100),"EndColor"=>new pColor(128,170,184,100)]); 
$myPicture->drawGradientArea(0,0,700,20, DIRECTION_VERTICAL, ["StartColor"=>new pColor(35,41,63,100),"EndColor"=>new pColor(35,41,63,100)]);

 
/*add a border */	
$myPicture->drawRectangle(0,0,699,229,["Color"=>new pColor(0,0,0)]);
 
/* Write the picture title */  
	
$myPicture->setFontProperties(["FontName"=>"fonts/tahoma.ttf","FontSize"=>10,"Color"=>new pColor(255,255,255)]);
$myPicture->drawText(10,20,"Progress Graph - ".$title,["FontSize"=>10]);
		
$myPicture->setFontProperties(["FontName"=>"fonts/tahoma.ttf","FontSize"=>16,"Color"=>new pColor(0,0,0)]);
	
$myPicture->drawText(350,225,"www.coachbergenroth.com");
	
 
/* Set the default font */ 
$myPicture->setFontProperties(["FontName"=>"fonts/tahoma.ttf","FontSize"=>6,"Color"=>new pColor(255,255,255)]);

/* Draw the scale */ 
$myPicture->setGraphArea(60,60,660,190); 
$myPicture->drawScale(); 
//$myPicture->drawBestFit(array("Color"=>new pColor(255,255,255),"Ticks"=>2,"Weight"=>6));
	
/* Turn on Anti-aliasing */
$myPicture->Antialias = TRUE;

/* Enable shadow computing */
$myPicture->setShadow(TRUE,["X"=>1,"Y"=>1,"Color"=>new pColor(0,0,0,10)]);	
	
	/* Create the pCharts object */
$pCharts = new pCharts($myPicture);
	
$pCharts->drawLineChart();
$pCharts->drawPlotChart(["DisplayValues"=>TRUE,"PlotBorder"=>TRUE,"BorderSize"=>2,"Surrounding"=>-60,"BorderColor"=>new pColor(0,0,0,80)]);

/* Write the chart legend */
$myPicture->drawLegend(590,9,["Style"=>LEGEND_NOBORDER,"Mode"=>LEGEND_HORIZONTAL,"FontColor"=>new pColor(255,255,255)]);
	
	
//$myPicture->drawFilledRectangle(0,0,700,230,["Color"=>new pColor(255,255,255),"Surrounding"=>-200,"Alpha"=>10]);
 
$myPicture->drawFromPNG(625,155,"images/rowingcoachinglogo_small.png");

//$myPicture->drawLineChart();

/* Render the picture (choose the best way) */ 
$myPicture->Render("images/scatter_" .$athleteid. ".png");
 
function YAxisFormat($Value) { return(round($Value/1000,2)."k"); } 
function XAxisFormat($Value) { return((($Value-1230768000)/(60*60*24))." day"); }
		
echo "<p class='imgcenter'><img src='images/scatter_".$athleteid.".png'></p>";
echo json_encode($myPicture->myData->getData());
		
	} else {
		
		echo "<p class='imgcenter'><br><br>No workout data, so no graph :(</p>";
	}

**Comment by bozhinov** [comment]
I shall try and figure it out tomorrow. Had a busy week. sorry

**Comment by bozhinov** [comment]
OK, so start from this example - example.createFunctionSerie.php

The reason your scale is upside down is cause your Y axis numbers start from high to low
you are also using NegateValues function. I don't think you need that, so just start over using the example code above

As for the format, I m not sure I follow. it is in seconds and it should be in ?

**Comment by bergenrothn97** [comment]
Thank you. It is in seconds and I would like to report it as follows:

100 secs = 1:40

**Comment by bergenrothn97** [comment]
The reason I need to flip the y axis is because a rower performing at 100 seconds per 500, is doing better than a rower performing at 110 second per 500m. So the lower number is better in this case the graph should be a higher line than the slower rower. Hope this makes sense.

**Comment by bergenrothn97** [comment]
Ok, thanks I will check it out.

**Comment by bozhinov** [comment]
Hi,
Any news on this ?
