### ISSUE TITLE
Unable to install it via composer

### ISSUE THREAD

**Issue by akram-kamboh** [bozhinov/pChart2.0-for-PHP7#20]
>composer require bozhinov/pChart2.0-for-PHP7

  [InvalidArgumentException]
  Could not find a matching version of package bozhinov/pChart2.0-for-PHP7. C
  heck the package spelling, your version constraint and that the package is
  available in a stability which matches your minimum-stability (stable).

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest]
 [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--
update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--pref
er-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authorita
tive] [--apcu-autoloader] [--] [<packages>]...

**Comment by bozhinov** [comment]
Try 
php composer.phar require bozhinov/pchart

packagist.org did not like that I used capital letters and dashes in the name
I had to clone the repo

**Comment by akram-kamboh** [comment]
Thanks @bozhinov

**Comment by akram-kamboh** [comment]
@bozhinov It's installed successfully with a warning

>composer require bozhinov/pchart
Using version ^2.2 for bozhinov/pchart
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing bozhinov/pchart (2.2.3): Downloading (100%)
Writing lock file
Generating autoload files
Warning: Ambiguous class resolution, "pChart\pDraw" was found in both vendor/bozhinov/pchart/pChart\pDraw.debug.php" and "vendor/bozhinov
/pchart/pChart\pDraw.php", the first will be used.

**Comment by bozhinov** [comment]
Repacked without that class.
Try now

**Comment by akram-kamboh** [comment]
Now, it's working fine

Thanks @bozhinov
