### ISSUE TITLE
Move text in scale when using LabelRotation

### ISSUE THREAD

**Issue by DaPeace** [bozhinov/pChart2.0-for-PHP7#21]
If i use LabelRotation -60 the Label is rotated but hanging too close to the line of the chart. Is there any possibility to move the label down? Did not find anything in the examples.
And by the way thank you for this fork!!

**Comment by bozhinov** [comment]
Hi,

I only noticed this. Holidays you know.

Can you please extract sample code ?

Momchil

**Comment by bozhinov** [comment]
@DaPeace  ?

**Comment by bozhinov** [comment]
Yep, that looks bad.
Can I have some sample code please ?

**Comment by DaPeace** [comment]
`/* CAT:Line chart */

/* Set the default timezone */
date_default_timezone_set('Etc/GMT');

/* pChart library inclusions */
require_once("bootstrap.php");

use pChart\pColor;
use pChart\pDraw;
use pChart\pCharts;

/* Create the pChart object */
$myPicture = new pDraw(700,310);
$myPicture->myData->addPoints($array1,"Temperatur");
$myPicture->myData->setAxisName(0,"Temperatur");
$myPicture->myData->setAxisName(0,"Temperatur");
$myPicture->myData->setAxisUnit(0,"Â°C");
$myPicture->myData->addPoints($array,"Labels");
$myPicture->myData->setAbscissa("Labels");
$myPicture->Antialias = FALSE;
$myPicture->drawFilledRectangle(0,0,700,310,["Color"=>new pColor(90,90,90), "Dash"=>TRUE, "DashColor"=>new pColor(120,120,120)]);
$Settings = ["StartColor"=>new pColor(200,200,200,50), "EndColor"=>new pColor(50,50,50,50)];
$myPicture->drawGradientArea(0,0,700,309,DIRECTION_VERTICAL,$Settings); 
$myPicture->drawGradientArea(0,0,700,309,DIRECTION_HORIZONTAL,$Settings); 
$myPicture->drawRectangle(0,0,699,309,["Color"=>new pColor(0,0,0)]);
$myPicture->setFontProperties(array("FontName"=>"pChart/fonts/Forgotte.ttf","FontSize"=>11));
$myPicture->drawText(100,25,"Textildruck Imst Temperatursensor",array("FontSize"=>18,"Align"=>TEXT_ALIGN_BOTTOMLEFT));
$myPicture->setFontProperties(array("FontName"=>"./pChart/fonts/Forgotte.ttf","FontSize"=>15,"R"=>255,"G"=>255,"B"=>255));
$myPicture->setGraphArea(60,40,680,250);
/*$myPicture->drawScale(array('XMargin'=>10,'YMargin'=>10,'LabelRotation'=>'-60','Floating'=>TRUE,'LabelingMethod'=>LABELING_DIFFERENT,'Pos'=>SCALE_POS_LEFTRIGHT, 'Mode'=>SCALE_MODE_ADDALL));*/
$myPicture->drawScale(array('XMargin'=>10,'YMargin'=>10,'LabelRotation'=>'-60','Floating'=>FALSE,'LabelingMethod'=>LABELING_DIFFERENT,'Pos'=>SCALE_POS_LEFTRIGHT, 'Mode'=>SCALE_MODE_ADDALL));

$myPicture->Antialias = TRUE;

/* Draw the line chart */
$myPicture->setShadow(TRUE,["X"=>1,"Y"=>1,"Color"=>new pColor(0,0,0,10)]);
(new pCharts($myPicture))->drawLineChart();

$myPicture->autoOutput("temp/example.drawSplineChart.network.png");

?>`

This is the code for this diagram. I hope it is readable..

**Comment by DaPeace** [comment]
Ohh.. really.. that easy :-)
Thank you very much. Now its way better!
