### ISSUE TITLE
Legacy Release and PHP 7.2.13

### ISSUE THREAD

**Issue by simogeo** [bozhinov/pChart2.0-for-PHP7#22]
hi @bozhinov. And first of all thanks for your work. 

I want my old pChart to work with PHP7. 
I've downloaded your [PHP7-compatible release](https://github.com/bozhinov/pChart2.0-for-PHP7/releases/tag/2.1.4a) but still, I experience some problem with PHP7.2.13 version (not tested with other PHP7 version).

Here are my errors : 

```
Warning: Illegal string offset 'XAxisDisplay' in /lib/vendor/pChart/class/pData.class.php on line 73

Warning: Illegal string offset 'XAxisFormat' in /lib/vendor/pChart/class/pData.class.php on line 74

Warning: Cannot assign an empty string to a string offset in /lib/vendor/pChart/class/pData.class.php on line 74
```

Do you still work on that version or not ? Is there another project maintaining PHP7 and pChart 2.1 compatibilty ? (didn't found)

Thanks for your answer.

**Comment by simogeo** [comment]
Sorry, it seems to be ok. I'll check this this afternoon and let you know ! 
Thanks

**Comment by bozhinov** [comment]
Hi, 

I will need some sample code to check it out.
The compatible branch should work though. 

Momchil

**Comment by simogeo** [comment]
My mistake, it works well ! Thanks again for the good job. :+1:
