### ISSUE TITLE
pChart 2.0 slow with php 5.6 ?

### ISSUE THREAD

**Issue by simogeo** [bozhinov/pChart2.0-for-PHP7#23]
I've just implemented pChart2 -for PHP 7 with php5.6 and it appears to be very slow.
Am I right or not ?

I could use both versions to optimize my app and make a test, but I'm sure you have some information regarding this. Thanks for your feeback.

I'll do further test on my own (and others hosts) later.

**Comment by bozhinov** [comment]
Hello,

I didn't think it was possible to even start it under PHP 5.6

If you share the code used for testing I could take a look

Momchil

**Comment by simogeo** [comment]
Here is the way I go (raw and partial extraction from my app) : 

```php

	/* pChart library inclusions */
	include_once("../lib/vendor/pChart-php7/class/pData.class.php");
	include_once("../lib/vendor/pChart-php7/class/pDraw.class.php");
	include_once("../lib/vendor/pChart-php7/class/pImage.class.php");
	
	/* Create and populate the pData object */
	$MyData = new pData();

	$MyDataThreshold = new pData();

	// ability for user to specify a palette for each individual indicator
	$palette = override('../dashboard/palettes/'.$id. '.color');
	if(file_exists($palette)) {
		$MyData->loadPalette($palette, TRUE);
	} else {
		$MyData->loadPalette(override('../dashboard/palettes/default.color'), TRUE);
	}

	// we loop on labels
	for ($k=0; $k<count($a_labels); $k++) {
		// echo join(', ', $stacked_data[$a_labels[$k]]).' - '. $a_labels[$k].'<br>';
		$MyData->addPoints($stacked_data[$a_labels[$k]], $a_labels[$k]);

	}

	$MyData->setAxisName(0,$unit);
	$MyData->addPoints($months,"Labels");
	$MyData->setSerieDescription("Labels","Months");
	$MyData->setAbscissa("Labels");
	
	
	/* Create the pChart object */
	$myPicture = new pImage($width, $height, $MyData);
	//$myPicture = new pImage(500,350,$MyData);
	
	/* Set the default font properties */
	$myPicture->setFontProperties(array("FontName"=>"../lib/vendor/pChart-php7/fonts/verdana.ttf","FontSize"=>8,"R"=>120,"G"=>120,"B"=>120));
	
	/* Draw the scale and the chart */
	$size = $myPicture->getLegendSize(array("Style"=>LEGEND_ROUND,"Mode"=>LEGEND_VERTICAL));
	$myPicture->setGraphArea($size["Width"] + 80, 20, $width - 20, $height - 50);
	
	/* Draw the scale */
	$scaleSettings = array(
            // grid settings
        "GridR" => 180,
        "GridG" => 180,
        "GridB" => 180,
        "GridTicks" => 1,
        "DrawSubTicks" => false, // ne pas afficher les entre ticks
        "Mode" => SCALE_MODE_ADDALL,
	    // axis color
	    "AxisR" => 200,
	    "AxisG" => 200,
	    "AxisB" => 200,
	    "CycleBackground" => true,
	    // background color 2
	    "BackgroundR2" => 240,
	    "BackgroundG2" => 240,
	    "BackgroundB2" => 240,
	    'LabelRotation' => 50,
        "DrawArrows" => FALSE,
	    "GridAlpha" => 30,
	    "TickAlpha" => 40
    );
	$myPicture->drawScale($scaleSettings);
	$myPicture->setShadow(FALSE);
	$MyData->setSerieDrawable("thresholds",FALSE);
	$myPicture->drawStackedBarChart(array("Surrounding"=>-15,"InnerSurrounding"=>15,
			"Rounded"=>false,
			// "Interleave" =>.5,
			"DisplayValues"=>true, "DisplayR"=>80, "DisplayG"=>80, "DisplayB"=>80,
			));
	
	
	/* Write the chart legend */
	$myPicture->drawLegend(20, $height - ($size["Height"] + 50),array("Style"=>LEGEND_NOBORDER,"Mode"=>LEGEND_VERTICAL,"Style"=>LEGEND_ROUND, "Alpha"=>20, ""));
	
	/* Render the picture (choose the best way) */
	if($display == true) {
			/* Render the picture - display it */
			$myPicture->autoOutput("simple.png");
		} else {
			/* Save the picture */
			if(!file_exists($workingpath)) mkdir($workingpath);
			$myPicture->render($workingpath.'/'.$id.'_'.$scale_id.'.png');
		}
```

**Comment by bozhinov** [comment]
OK I will give it a go the first chance I get
You are using the "Legacy" 2.1.4a correct ?

**Comment by simogeo** [comment]
thanks : 900x640px

**Comment by simogeo** [comment]
@bozhinov : I 'm using PHP 5.6.40 with your Legacy version on a remote host. Everything works correctly but it is very slow.

I downgraded to pChart original project version and it is still very slow .... I guess the issue is related to PHP version itself or something else ... I'll maybe do some tests on my localhost switching from php 7 to php 5 again.

I'll let you do - do not spend much time on this.

**Comment by bozhinov** [comment]
Hi, I will take a look at this after work but i believe it was slow cause there were warnings generated and you did not see those. Have you set the logging to E_ALL ?

**Comment by simogeo** [comment]
yep ... `error_reporting(E_ALL | E_STRICT);`

no error it seems ....

**Comment by bozhinov** [comment]
`<?php

## Start timer
$mtime = explode(" ",microtime());
$starttime = $mtime[1] + $mtime[0];

/* pChart library inclusions */
include_once("class/pData.class.php");
include_once("class/pDraw.class.php");
include_once("class/pImage.class.php");
	
$a_labels = array(
"aaaaa","VVVVVV"	
);

$stacked_data = array(
"aaaaa" => "12",
"VVVVVV" => "3"
);

$months = array(
	"January", "Feb"
);
/* Create and populate the pData object */
$MyData = new pData();

$MyData->loadPalette('palettes/kitchen.color');

// we loop on labels
for ($k=0; $k<count($a_labels); $k++) {
	$MyData->addPoints($stacked_data[$a_labels[$k]], $a_labels[$k]);
}

$MyData->setAxisName(0,"M");
$MyData->addPoints($months,"Labels");
$MyData->setSerieDescription("Labels","Months");
$MyData->setAbscissa("Labels");

/* Create the pChart object */
$myPicture = new pImage(900,640, $MyData);
//$myPicture = new pImage(500,350,$MyData);

/* Set the default font properties */
$myPicture->setFontProperties(array("FontName"=>"fonts/verdana.ttf","FontSize"=>8,"R"=>120,"G"=>120,"B"=>120));

/* Draw the scale and the chart */
$size = $myPicture->getLegendSize(array("Style"=>LEGEND_ROUND,"Mode"=>LEGEND_VERTICAL));
$myPicture->setGraphArea($size["Width"] + 80, 20, 900 - 20, 640 - 50);

/* Draw the scale */
$scaleSettings = array(
		// grid settings
	"GridR" => 180,
	"GridG" => 180,
	"GridB" => 180,
	"GridTicks" => 1,
	"DrawSubTicks" => false, // ne pas afficher les entre ticks
	"Mode" => SCALE_MODE_ADDALL,
	// axis color
	"AxisR" => 200,
	"AxisG" => 200,
	"AxisB" => 200,
	"CycleBackground" => true,
	// background color 2
	"BackgroundR2" => 240,
	"BackgroundG2" => 240,
	"BackgroundB2" => 240,
	'LabelRotation' => 50,
	"DrawArrows" => FALSE,
	"GridAlpha" => 30,
	"TickAlpha" => 40
);
$myPicture->drawScale($scaleSettings);
$myPicture->setShadow(FALSE);
$MyData->setSerieDrawable("thresholds",FALSE);
$myPicture->drawStackedBarChart(array("Surrounding"=>-15,"InnerSurrounding"=>15,
		"Rounded"=>false,
		// "Interleave" =>.5,
		"DisplayValues"=>true, "DisplayR"=>80, "DisplayG"=>80, "DisplayB"=>80,
		));


/* Write the chart legend */
$myPicture->drawLegend(20, 640 - ($size["Height"] + 50),array("Style"=>LEGEND_NOBORDER,"Mode"=>LEGEND_VERTICAL,"Style"=>LEGEND_ROUND, "Alpha"=>20, ""));

/* Render the picture (choose the best way) */
/* Save the picture */
$myPicture->render('sample.png');

## Stop timer
$mtime = explode(" ",microtime());
echo "Draw ".(($mtime[1] + $mtime[0]) - $starttime)." seconds";

?>`

That echoed 0.28 seconds. which seems decent. Ofc I had to fill in alot of missing variables to make your code work

**Comment by simogeo** [comment]
It is very strange. I really suspect my PHP version / config ...
Anyway, thanks for doing test

**Comment by bozhinov** [comment]
Nothing more we can do here
