### ISSUE TITLE
Series thresholds: non-numeric input issue

### ISSUE THREAD

**Issue by simogeo** [bozhinov/pChart2.0-for-PHP7#24]
Switching to your Legacy version I add to make a modification on my code because the new version triggered this error : `Series thresholds: non-numeric input`

passing SCALE_MODE_ADDALL mode solved the problem but my chart scale is not as wanted .... any clue of how / why pchart was able to catch min / man before and not in your proposed version ? 

Here is an extract of the code responsible of this behaviour (in pDraw.class.php) : 

```php
if ($Mode == SCALE_MODE_FLOATING || $Mode == SCALE_MODE_START0) {
				foreach($Data["Series"] as $SerieID => $SerieParameter) {
					if ($SerieParameter["Axis"] == $AxisID && $Data["Series"][$SerieID]["isDrawable"] && $Data["Abscissa"] != $SerieID) {
						if (!is_numeric($Data["Series"][$SerieID]["Max"]) || !is_numeric($Data["Series"][$SerieID]["Min"])){
							die("Series ".$SerieID.": non-numeric input");
						}
						$AxisMax = max($AxisMax, $Data["Series"][$SerieID]["Max"]);
						$AxisMin = min($AxisMin, $Data["Series"][$SerieID]["Min"]);
					}
				}

				(!is_numeric($AxisMin)) AND $AxisMin = 1; // $Data["Series"][$SerieID]["Min"] = Bulgium # MOMCHIL
				$AutoMargin = (($AxisMax - $AxisMin) / 100) * $XReleasePercent;
				$Data["Axis"][$AxisID]["Min"] = $AxisMin - $AutoMargin;
				$Data["Axis"][$AxisID]["Max"] = $AxisMax + $AutoMargin;
				if ($Mode == SCALE_MODE_START0) {
					$Data["Axis"][$AxisID]["Min"] = 0;
				} 
```

it is not easy for me to debug because I generate multiple charts calling my script ... but it seems I have this problem with area chart. 

I've also read this : 
http://wiki.pchart.net/doc.doc.draw.scale.html
http://wiki.pchart.net/doc.faq.scaling.html

**Comment by simogeo** [comment]
@bozhinov : I 've also seen this :https://github.com/bozhinov/pChart2.0-for-PHP7/issues/3

**Comment by bozhinov** [comment]
Casting stuff to int is never a good idea.
I mean, I did not add that line there. so it must be there for a reason

can you print_r the $Data before the script ends
.e.g add echo json_encode($Data); on line 2005 and move the die(* to 2006

**Comment by simogeo** [comment]
here is the dump : 

```json
xisDisplay":680001,"XAxisFormat":null,"XAxisName":null,"XAxisUnit":null,"Abscissa":"Dates","AbsicssaPosition":681002,"Axis":[{"Display":680001,"Position":681001,"Identity":682002,"Name":"number"}],"Series":{"2.a Score obtained at\u00a0the strategic planning assessment grid (implementation)":{"Description":"number","isDrawable":true,"Picture":null,"Max":"5","Min":"4","Axis":0,"Ticks":0,"Weight":0,"Shape":681011,"Color":{"R":188,"G":224,"B":46,"Alpha":100},"Data":["4","5"]},"thresholds":{"Description":"thresholds","isDrawable":true,"Picture":null,"Max":null,"Min":null,"Axis":0,"Ticks":0,"Weight":0,"Shape":681011,"Color":{"R":224,"G":100,"B":46,"Alpha":100},"Data":[null,null]},"Dates":{"Description":"Dates","isDrawable":true,"Picture":null,"Max":"04-12-15","Min":"04-04-18","Axis":0,"Ticks":0,"Weight":0,"Shape":681011,"Color":{"R":224,"G":214,"B":46,"Alpha":100},"Data":["04-12-15","04-04-18"]}},"GraphArea":{"X1":50,"Y1":20,"X2":880,"Y2":850}}
```

**Comment by simogeo** [comment]
indeed the min / max from thresholds serie ar null

> "thresholds": {"Description":"thresholds","isDrawable":true,"Picture":null,"Max":null,"Min":null,"Axis":0,"Ticks":0,"Weight":0,"Shape":681011,"Color":{"R":224,"G":100,"B":46,"Alpha":100},"Data":[null,null]}

don't know why and how to set them.

**Comment by bozhinov** [comment]
OK, I see Min and Max in the Series and in the thresholds->Dates, but not in thresholds root
does this work with pChart 2.1.4 from pchart.net ?

**Comment by bozhinov** [comment]
"Series":{
	"2.a Score obtained at\u00a0the strategic planning assessment grid (implementation)":{
		"Description":"number",
		"isDrawable":true,
		"Picture":null,
		"Max":"5",
		"Min":"4",
		"Axis":0,
		"Ticks":0,
		"Weight":0,
		"Shape":681011,
		"Color":{"R":188,"G":224,"B":46,"Alpha":100},
		"Data":["4","5"]
	},

These are strings and not int

**Comment by simogeo** [comment]
I'll have a look on that tomorrow, but according to the error message, the issue is not triggered by the serie you quoted but by "thresholds" serie.

**Comment by bozhinov** [comment]
but you only have 1 serie and it is the same one used for the threshold 
This has to be it

**Comment by simogeo** [comment]
hi @bozhinov : investigating a bit more, I don't really understand why values are passes as string (they are stored as float in db). Anyway, casting them does not solve the issue and does not same mandatory ... As said yesterday, because your pChart version is looking at min/max for `thresholds` series. 

Your version is less permissive than the old one. I'll solved my problem by adding a flag + test.

`if(!$is_null_threshold) $MyData->addPoints($ydata2,"thresholds");`

I identified a different behaviour also with stacked chart. I investigate on my own an let you know.

FYI, here is the json : 

```json
{
   "XAxisDisplay":680001,
   "XAxisFormat":null,
   "XAxisName":null,
   "XAxisUnit":null,
   "Abscissa":"Dates",
   "AbsicssaPosition":681002,
   "Axis":[
      {
         "Display":680001,
         "Position":681001,
         "Identity":682002,
         "Name":"number"
      }
   ],
   "Series":{
      "2.a Score obtained at\u00a0the strategic planning assessment grid (implementation)":{
         "Description":"number",
         "isDrawable":true,
         "Picture":null,
         "Max":5,
         "Min":4,
         "Axis":0,
         "Ticks":0,
         "Weight":0,
         "Shape":681011,
         "Color":{
            "R":188,
            "G":224,
            "B":46,
            "Alpha":100
         },
         "Data":[
            4,
            5
         ]
      },
      "thresholds":{
         "Description":"thresholds",
         "isDrawable":true,
         "Picture":null,
         "Max":null,
         "Min":null,
         "Axis":0,
         "Ticks":0,
         "Weight":0,
         "Shape":681011,
         "Color":{
            "R":224,
            "G":100,
            "B":46,
            "Alpha":100
         },
         "Data":[
            null,
            null
         ]
      },
      "Dates":{
         "Description":"Dates",
         "isDrawable":true,
         "Picture":null,
         "Max":"04-12-15",
         "Min":"04-04-18",
         "Axis":0,
         "Ticks":0,
         "Weight":0,
         "Shape":681011,
         "Color":{
            "R":224,
            "G":214,
            "B":46,
            "Alpha":100
         },
         "Data":[
            "04-12-15",
            "04-04-18"
         ]
      }
   },
   "GraphArea":{
      "X1":50,
      "Y1":20,
      "X2":880,
      "Y2":850
   }
}
```

**Comment by bozhinov** [comment]
Why thresholds at all if you are going to pass NULL values. Anyway. as long as it works for you

**Comment by simogeo** [comment]
Regarding the why ...  my code generates multiple charts based on multiples values / sources to embed them in a PDF document. Some charts have thresholds set, others not. 
I coded this in a way it what working as expected with pchart old version. I don't mind doing some changes.

**Comment by bozhinov** [comment]
The original version does not check much of the input. that has since changed (I believe for the better)

**Comment by ks1f14s** [comment]
@bozhinov you are a life saver :)
