### ISSUE TITLE
Laravel include

### ISSUE THREAD

**Issue by Dark-Hunter752** [bozhinov/pChart2.0-for-PHP7#25]
Hello there,
i'm wondering how i can use this library in my laravel project
using Laravel Framework 5.7.26
and 
php 7.2.10

**Comment by bozhinov** [comment]
Hi,

Try bozhinov/pchart with the composer

Momchil

**Comment by Dark-Hunter752** [comment]
hi, thanks for your response 
just for other :
i run in terminal : "composer require bozhinov/pchart"
and the library added to my vendor folder with your name 👍
------------------------------- 
but now i got a problem running  files and importing classes  giving me this error:
Illuminate\View\Engines\PhpEngine::main(): Failed opening required 
![image](https://user-images.githubusercontent.com/47715383/52916217-549d3800-32e5-11e9-9586-28d21c3cb74c.png)

changed the line as below and still not working
require_once("vendor/bozhinov/pchart/examples/bootstrap.php");

**Comment by bozhinov** [comment]
https://github.com/bozhinov/pChart2.0-for-PHP7/blob/master/examples/bootstrap.php
Here is my bootstrap, but the thing is you should have your own or simply include the parts of pChart you need

e.g. 
require_once("pChart\pColor.php"); 
require_once("pChart\pDraw.php"); 
require_once("pChart\pCharts.php");

**Comment by Dark-Hunter752** [comment]
Font Path Problem:
------------------------------- 
Ok Done ! thanks alot i understand namespace and bootstraps job!
 so i removed your require bootstrap and it seems that laravel load them automatically 
now my problem with path font.
![image](https://user-images.githubusercontent.com/47715383/52917294-6df8b100-32f2-11e9-8ca0-3bc8f6e09f6f.png)

**Comment by bozhinov** [comment]
that's a bug with PHP and not the script itself 
https://bugs.php.net/bug.php?id=75656
