### ISSUE TITLE
stacked chart issue related to min / max 

### ISSUE THREAD

**Issue by simogeo** [bozhinov/pChart2.0-for-PHP7#26]
hi @bozhinov,
Me again .....

I'm still experiencing some issues with your php7 fork. 
**By the way, I never told you, but many thanks for the work you did on that !**

Working with stacked chart now, I think there is an issue when using mode `SCALE_MODE_FLOATING` I guess calculated max value is just incorrect. The library is getting max value but working with stacked chart, it  should just do an addition of all values.

Here is the result working with `SCALE_MODE_FLOATING` : 
![pchart-bug](https://user-images.githubusercontent.com/154323/52942650-a8526480-336b-11e9-8e56-50cb0a9cee8b.png)

And with `SCALE_MODE_ADDALL` - rendering is correct but I get an unwanted squared image : 
![pchart-ok](https://user-images.githubusercontent.com/154323/52942711-c4ee9c80-336b-11e9-921a-04d80db9d63b.png)

Waiting for your feddback,
Thanks again

**Comment by bozhinov** [comment]
Hi,

and all of these worked OK with the original code from pchart.net ?

Momchil

**Comment by simogeo** [comment]
you're right. It did not work even in the original one ! 
I found & replaced all SCALE_MODE_ADDALL by SCALE_MODE_FLOATING when doing some tests - debugging other issues and that's how it happened.

Do not change anything, keep close to the original behavior.

Sorry for disturbing and thanks again for the lib.
