### ISSUE TITLE
Pigtail like datapoints

### ISSUE THREAD

**Issue by pierreverbakel** [bozhinov/pChart2.0-for-PHP7#27]
At using drawSplineChart() my graphs are shown with weird smoothing of the line connecting the points. I would use the name pigtails. Oddly enough it is not so for all datapoints. Looks like the Bezier calculation goes 'bizerk' like 180 degrees wrong ... Anyone else who has seen this behaviour between the original on PHP5.x
![graph_php_56](https://user-images.githubusercontent.com/15917988/55103341-82d21c80-50c8-11e9-905e-defaf60ae94c.png)
![graph_php_73](https://user-images.githubusercontent.com/15917988/55103355-8b2a5780-50c8-11e9-93e0-60cdf4005997.png)

 and the PHP 7.0 compatible?

**Comment by bozhinov** [comment]
That is weird indeed. I will need some sample code to troubleshoot it

**Comment by pierreverbakel** [comment]
The original data comes from a database, but I converted the data in arrays and made a testfunction, which indeed illustrates the difference when running on PHP Version 5.6.36-0+deb8u1 and the original pCharts-library, and when running on PHP Version 7.3.3-1+ubuntu18.04.1+deb.sury.org+1 and the library as I downloaded from https://github.com/bozhinov/pChart2.0-for-PHP7/tree/7.x-compatible

I have looked a bit in the code and see it is nicely re-done, I am wondering if there is a '+' and '-' exchanged in the calculation of the angle of the point-smoothing. I am not familiar very detailed into Bezier-formulas, so did not see the difference between the original code and the revamped-code so easily. I hope you have the better eye for that.

The PHP-Snippet to generate the graphic, see below:
// Include all the pChart-classes 
$PathToPcharts = './pchart/'; // Location of the pchart-library directory
include($PathToPcharts."class/pDraw.class.php");  ///< pDraw-Class for pCharts
include($PathToPcharts."class/pImage.class.php"); ///< pImage-Class for pCharts
include($PathToPcharts."class/pData.class.php");  ///< pData-Class for pCharts

function test_graphic(){ // Testdata for weird behaviour of smoothing in pchart drawSplineChart()
   global $PathToPcharts; 
   
   $x_axis_points_array = array (0 => '00', 1 => '0030', 2 => '01', 3 => '0130', 4 => '02', 5 => '0230', 6 => '03', 7 => '0330', 8 => '04', 9 => '0430', 10 =>'05', 11 =>'0530', 12 =>'06', 13 =>'0630', 14 =>'07', 15 =>'0730', 16 =>'08',
                                17 =>'0830', 18 =>'09', 19 =>'0930', 20 =>'10', 21 =>'1030', 22 =>'11', 23 =>'1130', 24 =>'12', 25 =>'1230', 26 =>'13', 27 =>'1330', 28 =>'14', 29 =>'1430', 30 =>'15', 31 =>'1530', 32 =>'16',
                                33 =>'1630', 34 =>'17', 35 => '1730', 36 => '18', 37 => '1830', 38 => '19', 39 => '1930', 40 => '20', 41 => '2030', 42 => '21', 43 => '2130', 44 => '22', 45 => '2230', 46 => '23', 47 => '2330', 48 => '00');

   $measurement_array = array(0 => 20.00, 1 => 23.00, 2 => 27.00, 3 => 26.89, 4 => 26.78, 5 => 26.67, 6 => 26.56, 7 => 26.44, 8 => 26.33, 9 => 26.22, 10 => 26.11, 11 => 26.00, 12 => 21.00, 13 => 29.00, 14 => 26.00, 15 => 25.00, 16 => 26.00, 17 => 26.00, 18 => 0.123456789, 19 => 0.123456789, 20 => 0.123456789,
      21 => VOID, 22 => VOID, 23 => VOID, 24 => VOID, 25 => VOID, 26 => VOID, 27 => VOID, 28 => VOID, 29 => VOID, 30 => VOID, 31 => VOID, 32 => VOID, 33 => VOID, 34 => VOID, 35 => VOID, 36 => VOID, 37 => VOID,
      38 => VOID, 39 => VOID, 40 => VOID, 41 => VOID, 42 => VOID, 43 => VOID, 44 => VOID, 45 => VOID, 46 => VOID, 47 => VOID, 48 => VOID);      

   $My_pChart_Graph_Object = new pData(); 

   echo "measurement_array:<br>\n";
   var_dump($measurement_array);
   
   $My_pChart_Graph_Object->addPoints($x_axis_points_array,"Timestamp");
   $My_pChart_Graph_Object->setAbscissa("Timestamp");

   $My_pChart_Graph_Object->setAxisName(0,'Air Quality Index');
   $My_pChart_Graph_Object->setAxisUnit(0,' Idx');
   
   // Save the measurement-data in the pData-Object '$My_pChart_Graph_Object'
   $My_pChart_Graph_Object->addPoints($measurement_array, 1);
   $My_pChart_Graph_Object->setSerieDescription(1, 'Hall');  
   
   // Create a pChart object and associate your dataset 
   //$myPicture = new pImage(700,230,$myData);
   $Image_Width = 1800;
   $Image_Height = 600;
   $myPicture = new pImage($Image_Width, $Image_Height, $My_pChart_Graph_Object);
   
   // Define the boundaries of the graph area 
   $GraphX_UL    = $Image_Width  * 0.06;
   $GraphY_UL    = $Image_Height * 0.15;
   $Graph_Width  = $Image_Width  * 0.8;
   $Graph_Height = $Image_Height * 0.65;
   
   $myPicture->setGraphArea($GraphX_UL, $GraphY_UL, $GraphX_UL + $Graph_Width, $GraphY_UL + $Graph_Height);
   
   // Set the Color of the Rectangle to be drawn 
   $Color_Settings = array("R"=>170, "G"=>183, "B"=>87); // Olive-green color #AAB757
   $myPicture->drawFilledRectangle(0, 0, $Image_Width, $Image_Height, $Color_Settings);
   
   // Define the Gradient-parameters: The Start-RGB and the End-RGB and the Alpha-value of the Layer
   $Gradient_Settings = array("StartR"=>219, "StartG"=>231, "StartB"=>139, "EndR"=>1, "EndG"=>138, "EndB"=>68, "Alpha"=>50);
   // Draw the Gradientlayer: Indicating XTOPLEFT,YTOPLEFT,XBOTTOMRIGHT,YBOTTOMRIGHT and the Direction 
   $myPicture->drawGradientArea(0, 0, $Image_Width-1, $Image_Height-1, DIRECTION_VERTICAL, $Gradient_Settings);
   $myPicture->drawRectangle(0, 0, $Image_Width-1, $Image_Height-1, array("R"=>0,"G"=>0,"B"=>0));

   $XAxis_Text_Fontsize = 10;
   $myPicture->setFontProperties(array("R"=>255,"G"=>255,"B"=>0,"FontName"=>$PathToPcharts."fonts/pf_arma_five.ttf","FontSize"=> $XAxis_Text_Fontsize));

   $Min_YAxis = 20;
   $Max_YAxis = 30;
   $AxisBoundaries = array(0=>array("Min"=>$Min_YAxis,"Max"=>$Max_YAxis));
   $ScaleSettings  = array("Mode"=>SCALE_MODE_MANUAL,
                           "ManualScale"=>$AxisBoundaries,
                           "DrawSubTicks"=>TRUE,
                           "DrawXLines"=>1 ,
                           "DrawArrows"=>FALSE,
                           "ArrowSize"=>6);
   $myPicture->drawScale($ScaleSettings);

   $XAxis_Text_X = intval($GraphX_UL  + 0.5 * $Graph_Width);
   $TextSettings = array("Align"=>TEXT_ALIGN_TOPMIDDLE, "R"=>255, "G"=>255, "B"=>0);
   $XAxis_Text = 'Time'; 
   $myPicture->setShadow(TRUE,array("X"=>2,"Y"=>2,"R"=>50,"G"=>50,"B"=>50,"Alpha"=>20));
   $myPicture->drawText($XAxis_Text_X,$Image_Height*0.84,$XAxis_Text,$TextSettings);
   
   $myPicture->drawSplineChart(); 
   
   $Output_FilenameAndPath = 'my_test_graph.png';
   $myPicture->render($Output_FilenameAndPath);
   echo 'Graphic-File created as :'.$Output_FilenameAndPath."<br>\n";
   echo '<img src="'.$Output_FilenameAndPath.'">';
} // End of test_graphic()

![graph_php_56](https://user-images.githubusercontent.com/15917988/55103341-82d21c80-50c8-11e9-905e-defaf60ae94c.png)
![graph_php_73](https://user-images.githubusercontent.com/15917988/55103355-8b2a5780-50c8-11e9-93e0-60cdf4005997.png)

**Comment by bozhinov** [comment]
That helped quite a bit. Thank you.
I migrated your code to the new version and the problem is there as well

It will take some time to dig deeper, but so far the scaling does not work properly
pDraw->scaleComputeY()
The more values you add the worse it gets

Poor refactoring on my end. sorry.

**Comment by pierreverbakel** [comment]
Glad that you could reproduce the problem. Previously I stated that the problem does not happen at all points, but I see now that in the datapoints when they are extremely different one after another that the efect is less noticable. Thanks for looking into it. I think it is a great library with a lot of capabilities and want to stick using it.

**Comment by bozhinov** [comment]
OK so the problem was with drawSplineChart only. Which is good. 
It's late and I only fixed it for the Master branch
I hope to have some time tomorrow to do it for the compat as well

**Comment by bozhinov** [comment]
OK it should be good to go

**Comment by pierreverbakel** [comment]
I have tried out the change to pDraw.class.php, which was a bit more than a + or a -1. Something with a parameter that should have been an array and a lot of other things, so for me this issue can be closed :) 
At least the test now brings the same result as on a PHP5.6 platform with the original library. 

PS: Is there any documentation on what it means to move up with the updated versions. Since I understand they are not backwards compatible. It would be good how upgrading path looks like for existing implementations using the original pChart library.

**Comment by pierreverbakel** [comment]
Closing the issue.

**Comment by bozhinov** [comment]
Hi, the "documentation" for the old one is the sandbox and all the examples
Those have been migrated to the new framework. You can check the bugs/bug27.php in the Master branch to how your code would look like
