### ISSUE TITLE
Non-numeric value in pDraw.class.php

### ISSUE THREAD

**Issue by fradelg** [bozhinov/pChart2.0-for-PHP7#3]
First of all thank you very much for migrating this library to PHP 7.

I've found an issue with new PHP warning: 

```
A non-numeric value encountered in class/pDraw.class.php on line 2005 and class/pDraw.class.php on line 2007
```

I've solved by casting to float the variables

```php
$AutoMargin = (((float)$AxisMax - (float)$AxisMin) / 100) * (float)$XReleasePercent;
$Data["Axis"][$AxisID]["Min"] = $AxisMin - $AutoMargin;
$Data["Axis"][$AxisID]["Max"] = (float)$AxisMax + (float)$AutoMargin;
```

I'm sure there is a better solution but this is just a quick and dirty fix.

Regards

**Comment by bozhinov** [comment]
You are welcome :)

Can I have your use case ?
Quick & dirty is ok for any upper level class, but not here

**Comment by bozhinov** [comment]
Javier ?

**Comment by fradelg** [comment]
I've dived into the issue till I've found that the problem is mine. 

I am using SCALE_MODE_START0 in drawScale without setting data series correctly (actually there are two series but both are empty). So I have `$Data["Series"][$SerieID]["Max"] = ""` in line 1999

I fix my code to overcome the issue but I think that the code 

```php
(!is_numeric($AxisMax)) AND $AxisMax = 100;
``` 

in line 2006 will be enough to workaround the issue as a fallback mode.

You decide whether this is something useful for the library or not.

**Comment by bozhinov** [comment]
To be honest the lib should point such errors out and not cover them.
I will add an extra check

**Comment by fradelg** [comment]
Thanks!

Actually it isn't an error, it is just a warning introduced by PHP 7.1.

More info at [migrating to PHP 7.1](https://secure.php.net/manual/en/migration71.other-changes.php)

**Comment by bozhinov** [comment]
Please if this works with your use case:
Add after line: 1998
if (!is_numeric($Data["Series"][$SerieID]["Max"]) || !is_numeric($Data["Series"][$SerieID]["Min"])){
	die("Series ".$SerieID.": non-numeric input");
}

**Comment by fradelg** [comment]
Yes, it works!

But wouldn't be better to use the loop variable `$SerieParameter` instead of `$Data["Series"][$SerieID]`? Aren't they equivalent?

Thanks!

**Comment by bozhinov** [comment]
I think it includes it but is not limited to
so Jean-Damien used it like this few lines down so it is't better this way. 

Thank you for the test
