### ISSUE TITLE
Pie chart and zero values

### ISSUE THREAD

**Issue by roblevine82** [bozhinov/pChart2.0-for-PHP7#31]
Having trouble with this:  When one of the values passed to addPoints for a pie chart is zero, the code correctly doesn't display a slice, but it doesn't increment it's position in the label array; so labels after any 0 in the addPoints get shifted

 $nValues = [2,1,0,0,31,63,2]; 
 $myPicture->myData->addPoints($nValues,"Demo");  
 $myPicture->myData->setSerieDescription("Demo","Percent of demographic");
 $labelArray = ["Two or more","Black","Hawaiian PI","Native American","White","Asian","Hispanic Latino"];
 $myPicture->myData->addPoints($labelArray,"Labels");
 $myPicture->myData->setAbscissa("Labels"); 

The slices labeled Hawaiian an Native American should actually be the White and Asian slices.

![pie](https://user-images.githubusercontent.com/71185035/93027502-e6108100-f5d2-11ea-9557-5980db54eca5.jpg)

**Comment by bozhinov** [comment]
I guess that's fixable on your end as well ?
I don't have much time right now, but if you provide me a fully functioning code, I can see what I can do about it

**Comment by roblevine82** [comment]
Thanks.  If you could point me to the method that iterates the slices maybe I can fix it...thanks again for your work on this project!

**Comment by roblevine82** [comment]
Here's the code that will produce the problem; two items in array are 0 - no slices shown is correct - but labels aren't incremented.


/* pChart library inclusions */
require_once("bootstrap.php");
require_once("functions.inc.php");

use pChart\pColor;
use pChart\pDraw;
use pChart\pPie;

/* Create the pChart object */
$myPicture = new pDraw(700,700);	
 /* Create and populate the pData object */
 $nValues = [2,1,0,0,31,63,2]; 
 $myPicture->myData->addPoints($nValues,"Demo");  
 $myPicture->myData->setSerieDescription("Demo","Percent of demographic");
 $labelArray = ["Two or more","Black","Hawaiian PI","Native American","White","Asian","Hispanic Latino"];
 $myPicture->myData->addPoints($labelArray,"Labels");
 $myPicture->myData->setAbscissa("Labels"); 
$myPicture->setFontProperties(array("FontName"=>"fonts/verdana.ttf","FontSize"=>10, "Color"=> new pColor(0,0,0)));				 
$PieChart = new pPie($myPicture); 
$myPicture->setFontProperties(["FontName"=>"fonts/Cairo-Regular.ttf","FontSize"=>9,"Color"=>new pColor(80)]);
$PieChart->draw3DPie(400,400,["WriteValues"=>TRUE,"DrawLabels"=>TRUE,"DataGapAngle"=>12,"DataGapRadius"=>10,"Border"=>TRUE]);
$PieChart->drawPieLegend(210,25,["Style"=>LEGEND_NOBORDER,"Mode"=>LEGEND_VERTICAL]);
$myPicture->setFontProperties(array("FontName"=>"fonts/verdana.ttf","FontSize"=>10));
$myPicture->drawText(45,15,"Race/Ethnicity",array("FontSize"=>9,"Align"=>TEXT_ALIGN_BOTTOMLEFT)); 
 $myPicture->autoOutput();

**Comment by bozhinov** [comment]
Thank you for this. I will take a look as soon as I can

**Comment by bozhinov** [comment]
Pushed to master. Try now

**Comment by roblevine82** [comment]
Works! Thank you so much
