### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'pChart\pColor' not found in ...\pChart\pData.php:27

### ISSUE THREAD

**Issue by MarcelloDM** [bozhinov/pChart2.0-for-PHP7#32]
Hi, I tried to install and integrate that pChart module object in my  project.

But I get the error as follow: 
`PHP Fatal error:  Uncaught Error: Class 'pChart\pColor' not found in ...\pChart\pData.php:27` 

I checked the namespace is correct but I did not solve. Does anyone get the same  problem?

**Comment by bozhinov** [comment]
and pColor.php is included ?
May I see your code ?

**Comment by bozhinov** [comment]
I guess your figured it out.
