### ISSUE TITLE
Can't find ImageMapper for onMouseOver info.

### ISSUE THREAD

**Issue by gabolander** [bozhinov/pChart2.0-for-PHP7#36]
First of all, thank you for your awesome work to clean up code of this project and make it live against newest php versions!
The only issue I have to report is that I couldn't be able to use an alternative imagemap or make "onmouseover" work, like in the past" on the chart to see the values in the baloons in corrispondence, for instance, of the bars of the charts or the pie's slices, etc... 
Any suggetions ?
Thank you and keep up the good job! ;-)

**Comment by bozhinov** [comment]
Hi, glad someone is still using anything but JS for web
I dropped ImageMapper in 2.3 but you are welcome to try 2.2
I spent some time on rewriting it in jQuery. you may very well be the only consumer of that code :)

**Comment by gabolander** [comment]
May be I'm the only one, LOL xD ... but the users of my web portal wonder why they missed that feature after I migrated to php7 ... So what can I do? wait for you to implement in JQuery or try other by my own?
Thank you for your answers.

**Comment by bozhinov** [comment]
It is already implemented in jQuery
branch 2.2 is totally ok to use
