### ISSUE TITLE
"pChart: Trying to draw outside of image dimentions"

### ISSUE THREAD

**Issue by Mescl1t0** [bozhinov/pChart2.0-for-PHP7#37]
I use dynamic data for the graph. Sometimes I get an error. 
Fatal error: Uncaught pChart\pException: pChart: Trying to draw outside of image dimentions. in /var/www/html/mia/pChart/pException.php:25 Stack trace: #0 /var/www/html/mia/pChart/pDraw.php(1114): pChart\pException::InvalidCoordinates('Trying to draw ...') #1 /var/www/html/mia/pChart/pDraw.php(831): pChart\pDraw->drawAntialiasPixel(160.8280787926, -0.070196981508373, Object(pChart\pColor)) #2 /var/www/html/mia/pChart/pDraw.php(277): pChart\pDraw->drawLine(156, 12, 164, -8, Array) #3 /var/www/html/mia/pChart/pDraw.php(814): pChart\pDraw->drawPolygon(Array, Array) #4 /var/www/html/mia/pChart/pCharts.php(533): pChart\pDraw->drawLine(156, 12, 164, -9, Array) #5 /var/www/html/mia/inc/draw_pchart.inc(364): pChart\pCharts->drawLineChart() #6 /var/www/html/mia/1hall.php(24): include('/var/www/html/m...') #7 {main} thrown in /var/www/html/mia/pChart/pException.php on line 25

**Comment by bozhinov** [comment]
Hi,

Try starting from 1 pixel higher

Frankly, this exception can be commented out but it does reveals problems with the math behind generating the objects
