### ISSUE TITLE
Unexpected zero values on chart

### ISSUE THREAD

**Issue by semirke** [bozhinov/pChart2.0-for-PHP7#38]
Hi, 

  seems every second value is charted as zeroes when rendering a line chart. 
  I use the code provided in the examples, a network line chart. 
![image](https://user-images.githubusercontent.com/2180225/135221198-046e7431-e69b-413f-bd2c-39894f3350f7.png)

  I bang my head to my desk since yesterday afternoon with no avail.
  I checked the data, it doesnt have these zeroes, nor does it have gaps and the number of items in the X axis series matches both Y val series. X series is monotonicly increasing. 

  Data points arrive at every 5-10 seconds, with high jitter. Maybe that is important, but I tried to replace the BaseTsArr with generated timestamps with the same result.

  Any ide what could cause this?

```php
  $end = time();
  $data = $db->getPortValue($res, $end, $host, $port);
  
  /* Create the pChart object */
  $myPicture = new pDraw(700,230);

/* Populate the pData object */
$LastInArr = [];
$LastOutArr = [];
$BaseTsArr = [];

foreach($data as $d)
{
    $arr[$d["ts"]][$d["name"]] = $d["value"];
}

foreach($arr as $k=>$d)
{
    $LastInArr[] = floor($d["'rx'"]);
    $LastOutArr[] = floor($d["'tx'"]);

    $BaseTsArr[]  = $k; 

}
$myPicture->myData->addPoints($LastInArr,"Inbound");
$myPicture->myData->addPoints($LastOutArr,"Outbound");
$myPicture->myData->addPoints($BaseTsArr,"TimeStamp");

$myPicture->myData->setAxisProperties(0, ["Name" => "Bandwidth", "Display" => AXIS_FORMAT_TRAFFIC]);
$myPicture->myData->setSerieDescription("TimeStamp","time");
$myPicture->myData->setAbscissa("TimeStamp", ["Display" => AXIS_FORMAT_DATE, "Format" => "H:i"]);

/* Turn off Anti-aliasing */
$myPicture->setAntialias(FALSE);

/* Draw a background */
$myPicture->drawFilledRectangle(0,0,700,230,["Color"=>new pColor(120), "Dash"=>false, "DashColor"=>new pColor(120)]);
````

And it goes on as the original example.

The help would be really appretiated :) 

Thanks,
Semir

**Comment by bozhinov** [comment]
Hi,

Please serialize $data for me.
Json it or something

Momchil

**Comment by semirke** [comment]
Thank you for your quick response. 
Please find it here: [https://pchart.profivps.hu/render2.php](url)

**Comment by bozhinov** [comment]
I will have a look at it later today
it could be something with the scaling - the range of "value" is wide

**Comment by semirke** [comment]
Thank you, it'd be most appretiated!

**Comment by bozhinov** [comment]
Hello,

I was able to reduce the input to this: 
[{"id":"322","ts":"1632943385","name":"rx","value":"2150319.302952"},
{"id":"379","ts":"1632943391","name":"rx","value":"9410.24716"}]

which is basically a single line that when drawn goes all the way to 0
problem is the first value is 2.05Mb and the second is 0.009Mb
I don't see a way to scale this so it is visible and none 0

sorry,
Momchil

**Comment by semirke** [comment]
Hmmm, 
thank you, you actually helped me a lot. 
So my data is errenous. I dont know how I failed to realize it...

Thanks!

**Comment by semirke** [comment]
Man... You did help me a lot... I was sooo dumb...
Thanks again...

**Comment by bozhinov** [comment]
No problem
