### ISSUE TITLE
Thank you for creating this fork

### ISSUE THREAD

**Issue by mattab** [bozhinov/pChart2.0-for-PHP7#4]
Hello there,

We are @Piwik the open source alternative to Google Analytics. We use pChart to generate our analytics charts sent by email. We'd love to use your project. In particular we got several reports of PHP7 compat issues in https://github.com/piwik/piwik/issues/11116 

Just wanted to say thanks and good luck. I hope we can use your project soon!

**Comment by bozhinov** [comment]
Hello,

You are welcome.
Anything you need from my end just let me know

Momchil
