### ISSUE TITLE
Array as result in leads to error in php 56

### ISSUE THREAD

**Issue by mesa57** [bozhinov/pChart2.0-for-PHP7#5]
I get : 
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/spotweb/vendor/pchart/class/pDraw.class.php on line 619

When I use pchart in php 56.
Seems that that array as result in 
```
	/* Drawn a spline based on the bezier function */
	function drawSpline(array $Coordinates, array $Format = []) : array {

```
is only compatible with php 7 and higher.
When I leave out the result declaration the error is gone.

**Comment by bozhinov** [comment]
Hi,

Sorry, this fork only work on PHP 7+

For version 5.6 please use the original source from http://www.pchart.net/

Momchil

**Comment by mesa57** [comment]
As our application ( https://github.com/spotweb/spotweb ) is used by thousands of people on all kind of operating systems we need to support php 5.6 - 7.1
I will test if my proposed change breaks anything. 
Another question : are you going to register this for with packagist ?

**Comment by bozhinov** [comment]
I had to google packagist. I guess I can register

As for the 5.x support, I think the only breaking change was the use of parameter and return declarations
I will probably create a separate brach but I need to finish my current project first so no ETA, sorry

**Comment by bozhinov** [comment]
The other thing that worries me is that this is not my code, I just refactored it
I did contact Jean-Damien and told him about this repo, but has not responded yet although it has been a while

**Comment by mesa57** [comment]
I think Jean-Damien has left the scene as pChart was last updated in 2014.
If he was still around we should not need you're fork I suppose.
Btw. you're fork was recommended by one of out users who was confronted with a non working pchart in php 7.1

**Comment by bozhinov** [comment]
please check out the 5.x-Compatible branch

**Comment by mesa57** [comment]
As I look at the changes I am asking myself if this is not to much ?
I only had a problem we're a function was declared with a typed return result like : 
`function drawSpline(array $Coordinates, array $Format = []) : array {`
Removing the array as type result works perfectly
`function drawSpline(array $Coordinates, array $Format = []) {`
I my opinion that's the only needed change ?

**Comment by mesa57** [comment]
Test results : 
Debian Jessie/php 5.6.x :ballot_box_with_check:

**Comment by bozhinov** [comment]
Well, still better to use the 5.x-Compatible branch
It includes the change that you suggested

All unit tests green is always a cause to pop a beer open ;)

**Comment by mesa57** [comment]
For the time being we will continue with the fix as described by me. When the package is added to packagist I will install it again and re-execute the tests.
Thank you for you're coörperation 👍
