### ISSUE TITLE
pCache goes into infinite loop, if file handle is false

### ISSUE THREAD

**Issue by cyberbeat** [bozhinov/pChart2.0-for-PHP7#7]
in pCache line 169 and following
..
while (!feof($Handle)) {
..

if the $Handle is not a ressource, for example false, there is an endless loop, and the server error log may be fill the entire disk like this:

[Tue Nov 21 16:00:17.534326 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  feof() expects parameter 1 to be resource, boolean given in ...pCache.class.php on line 176, referer: ...
[Tue Nov 21 16:00:17.534329 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  ftell() expects parameter 1 to be resource, boolean given in ...pCache.class.php on line 177, referer: ...
[Tue Nov 21 16:00:17.534332 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in ...pCache.class.php on line 178, referer: ...
[Tue Nov 21 16:00:17.534335 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  feof() expects parameter 1 to be resource, boolean given in ...pCache.class.php on line 176, referer: ...
[Tue Nov 21 16:00:17.534338 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  ftell() expects parameter 1 to be resource, boolean given in ...pCache.class.php on line 177, referer: ...
[Tue Nov 21 16:00:17.534341 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in ...pCache.class.php on line 178, referer: ...
[Tue Nov 21 16:00:17.534344 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  feof() expects parameter 1 to be resource, boolean given in ...pCache.class.php on line 176, referer: ...
[Tue Nov 21 16:00:17.534348 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  ftell() expects parameter 1 to be resource, boolean given in ...pCache.class.php on line 177, referer: ...
[Tue Nov 21 16:00:17.534351 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in ...pCache.class.php on line 178, referer: ...
[Tue Nov 21 16:00:17.534354 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  feof() expects parameter 1 to be resource, boolean given in ...pCache.class.php on line 176, referer: ...
[Tue Nov 21 16:00:17.534357 2017] [fcgid:warn] [pid 23480] [client ...] mod_fcgid: stderr: PHP Warning:  ftell() expects parameter 1 to be resource

**Comment by cyberbeat** [comment]
A workaround may be

while ($handle && !feof($Handle)) {

**Comment by bozhinov** [comment]
Thank you for that. 

The original code is supressing all these warnings, but that method no longer works for PHP7+
I have removed all that and added checks for all handles before using them
